### ISSUE TITLE
路由器上配置的rc，监听应该怎么写？

### ISSUE THREAD

**Issue by cikichen** [mlkt/openwrt-mipsel-cow#2]
监听所有的访问 0.0.0.0，但是会提示丢失端口

**Comment by mlkt** [comment]
和在电脑上一样啊
listen = http://0.0.0.0:7774

你要确保后面端口没有和系统已有冲突

或者你试试用路由器的IP，比如：
listen = http://192.168.1.1:7774

**Comment by cikichen** [comment]
这样还是需要去浏览器设置pac吧，有办法不做任何设置就能直接让所有请求经过么

**Comment by cikichen** [comment]
另外能提供下开机启动脚本吗

**Comment by mlkt** [comment]
要直接转向用iptables+redsock
